### ISSUE TITLE
[FlakyTest] ServiceControlCliArgumentsSuite

### ISSUE THREAD

**Issue by cfmcgrady** [apache/incubator-kyuubi#2430]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the subtask

https://lists.apache.org/thread/g0ydjyo9893f0dvvmgg3sgkkfcr2xzm6

```
Run starting. Expected test count is: 24
ServiceControlCliArgumentsSuite:
- test basic kyuubi service arguments parser *** FAILED ***
  "[zhangduo-ubuntu]" did not equal "[localhost]"
(ServiceControlCliArgumentsSuite.scala:99)
  Analysis:
  "[zhangduo-ubuntu]" -> "[localhost]"
- prints usage on empty input
- prints error with unrecognized options
- test invalid arguments
- test extra unused arguments
- test list action arguments
- test get/delete action arguments
- test with unknown host
- test with invalid port specification
- test create action arguments
- test use default property value if missing
- test use short options *** FAILED ***
  "[zhangduo-ubuntu]" did not equal "[localhost]"
(ServiceControlCliArgumentsSuite.scala:333)
  Analysis:
  "[zhangduo-ubuntu]" -> "[localhost]"
- test --help
```

### Parent issue

#1733 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!
