### ISSUE TITLE
[SUB-TASK][KPIP-4] Implement restClient for batch job submission

### ISSUE THREAD

**Issue by turboFei** [apache/incubator-kyuubi#2628]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

sub-task of #2240 

Thanks the docs drafted by @ulysses-you 
https://docs.google.com/document/d/1GQQXzC0GdXdKwGI0DiO04pa9N3AAixuuo1B4j6EI2AA/edit#heading=h.e8opx7al2u29

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ulysses-you** [comment]
@turboFei do you want add a rest client module for the functionality of sdk ?

**Comment by turboFei** [comment]
@turboFei do you want add a rest client module for the functionality of sdk ?

Yeah.

**Comment by ulysses-you** [comment]
I'm fine with this, and for user-faced interface, we need better docs. cc @yaooqinn

**Comment by turboFei** [comment]
cc @lightning-L are you interested in this?

**Comment by lightning-L** [comment]
> cc @lightning-L are you interested in this?

of course..

**Comment by turboFei** [comment]
let us wait for more discussions on this.

**Comment by turboFei** [comment]
Please refer the docs: https://docs.google.com/document/d/1GQQXzC0GdXdKwGI0DiO04pa9N3AAixuuo1B4j6EI2AA/edit#heading=h.e8opx7al2u29

```
  Support kyuubi batch command in existing kyuubi-ctl
  From:
   Usage: kyuubi-ctl [create|get|delete|list] [server|engine] [options]

   To:

   Usage: kyuubictl [create|get|delete|list|logs|submit] [resource] [options]
   resources: [server|engine|batch]
```
